project:
  type: website
  render:
    - about.qmd
    - index.qmd
    - there-was-pi.qmd
    - 404.qmd

website:
  title: "in-the-beginning"
  site-url: https://mad0perator.github.io/in-the-beginning
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: there-was-pi.qmd
        text: ...there was $\Pi$
    tools:
      - icon: twitter
        href: "https://twitter.com/@null_space"
      - icon: github
        url: "https://github.com/mad0perator/in-the-beginning"
  repo-url: "https://github.com/mad0perator/in-the-beginning"
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@null_space"
    site: "@mad0perator"
  open-graph:
    locale: en_US
  page-navigation: true
  #back-to-top-navigation: true
  page-footer: >-
    This website is written using [Quarto]({{< var about.websites >}}).</br>
    Copyright 2023, mad0perator

format:
  html:
    theme:
      light: flatly
      dark: cyborg
    code-fold: true
    code-tools: true
    page-layout: full
    css: styles.css
    toc: true
    html-math-method: katex

editor:
  markdown:
    wrap: 72
    


