project:
  type: website

website:
  title: "The Genesis Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  markdown:
    wrap: 72
    references:
      location: block
      links: true


