# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/in-the-beginning',
                'doc_host': 'https://mad0perator.github.io',
                'git_url': 'https://github.com/mad0perator/in-the-beginning',
                'lib_path': 'in_the_beginning'},
  'syms': {'in_the_beginning.core': {'in_the_beginning.core.foo': ('core.html#foo', 'in_the_beginning/core.py')}}}